### PR TITLE
Fix open output stream

### PR DESCRIPTION
**Pull request by sakama**
Revised of #29 and #30

### CODE REVIEW

**Comment by sakama** [comment]
@muga How do you think about?

**Comment by muga** [comment]
Sorry, I still not sure, please explain how this fix work?

**Comment by sakama** [comment]
Sorry for late.
At #30, I implemented retry logic in `uploadFile()` method and this method create new BufferedOutputStream at every retry.
But this `uploadFile()` is called at every `add()` calls and should cause something troubles..
https://github.com/embulk/embulk-output-sftp/pull/29/files#diff-224baa6e670e84c6b9619558173f980dR180

Then, I changed implementation only create new BufferedOutputStream at the first time.
This means new BufferedOutputStream will be created only when `nextFile()` is called.

**Comment by sakama** [comment]
I talked with @muga and it's better that once write at temporary file.

**Pull request closed without merging**
