### PR TITLE
Handle cases when the file's parent is nil when the output format is selected in JSONL and runs parallel. 

### PR DESCRIPTION
**Pull request by pn-koshikawa**
- why
  - To handle the case that a file's parent becomes nil when the output format is selected in JSONL and runs parallel.
- what
  - Checked the parent of the file and took action so that an error is not generated if the parent of the file is nil.
- Not to be addressed in this PR.
  - Only null handling is performed first, and the highest priority is not dropping the process due to an error so does not address the issue of files not being generated with the specified path when executed in parallel.

### CODE REVIEW

**Comment by pn-koshikawa** [comment]
@dmikurube @luongnhattruong 

Hello. Due to permissions, I didn't seem to be able to set up a reviewer, so I would be happy if you could review this PR.
Best regards.

**Comment by dmikurube** [comment]
Thanks for your contribution. But, sorry that I don't understand this part :

> To handle the case that a file's parent becomes nil when the output format is selected in JSONL and runs parallel.

What does this mean?  When/why/how such a case happens?

> Checked the parent of the file and took action so that an error is not generated if the parent of the file is nil.

Is skipping really an appropriate way?  Such the case does not look like an expected behavior, then I thought that raising an error could be better.

**Comment by pn-koshikawa** [comment]
@dmikurube 
Thanks. It occurred when several hundred records were prepared as input (in this case, I used BigQuery as an input plugin), [embulk-formatter-jsonl](https://github.com/takei-yuya/embulk-formatter-jsonl), and min_output_tasks were executed greater than 1.

```
in:
...
out:
  type: sftp
  ...
  user_directory_is_root: true
  path_prefix: "/path/to/dir"
  file_ext: json
  formatter:
    type: jsonl
    encoding: UTF-8
    newline: LF
  sequence_format: "."
stop_on_invalid_record: true
```

```
[INFO] (0001:transaction): Using local thread executor with max_threads=4 / output tasks 2 = input tasks 1 * 2
```

I have masked the confidential information, but first output task completes the upload successfully, but second output tasks treat the upload file as null, resulting in an error.

```
[INFO] (0001:transaction): Using local thread executor with max_threads=4 / output tasks 2 = input tasks 1 * 2
[INFO] (0001:transaction): Loaded plugin embulk-formatter-jsonl (0.1.4)
[INFO] (0001:transaction): {done:  0 / 1, running: 0}
[INFO] (0024:task-0000): {speedometer: {active: 0, total: 0.0b, sec: 0.00, speed: 0.0b/s, records: 0, record-speed: 0/s}}
[INFO] (0024:task-0000): Start download : xxxx ...to ... xxxx
[INFO] (0024:task-0000): parent directory xxxxdata exists there
[INFO] (0024:task-0000): Uploading to remote sftp file (11 KB): xxxx
[INFO] (0024:task-0000): Upload completed.
[INFO] (0024:task-0000): {speedometer: {active: 0, total: 5.1kb, sec: 0.71, speed: 7.1kb/s, records: 92, record-speed: 128/s}}
[WARN] (0024:task-0000): SFTP upload file 'null' failed. Retrying 1/5 after 0 seconds. Message: null
[WARN] (0024:task-0000): SFTP upload file 'null' failed. Retrying 2/5 after 1 seconds. Message: null
[WARN] (0024:task-0000): SFTP upload file 'null' failed. Retrying 3/5 after 2 seconds. Message: null
java.lang.NullPointerException: null
	at org.embulk.output.sftp.SftpUtils.newSftpFile(SftpUtils.java:293) [embulk-output-sftp-0.2.1.jar:na]
	at org.embulk.output.sftp.SftpUtils$1.call(SftpUtils.java:160) ~[na:na]
	at org.embulk.output.sftp.SftpUtils$1.call(SftpUtils.java:156) ~[na:na]
	at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:81) [embulk:0.9.26]
	at org.embulk.spi.util.RetryExecutor.runInterruptible(RetryExecutor.java:62) [embulk:0.9.26]
	at org.embulk.output.sftp.SftpUtils.withRetry(SftpUtils.java:321) [embulk-output-sftp-0.2.1.jar:na]
	at org.embulk.output.sftp.SftpUtils.uploadFile(SftpUtils.java:155) [embulk-output-sftp-0.2.1.jar:na]
	at org.embulk.output.sftp.SftpLocalFileOutput.flush(SftpLocalFileOutput.java:208) [embulk-output-sftp-0.2.1.jar:na]
	at org.embulk.output.sftp.SftpLocalFileOutput.finish(SftpLocalFileOutput.java:118) [embulk-output-sftp-0.2.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_372]
```

The first task transfers files to the specified path_prefix, but the second one is executed as root directory instead of the specified path_prefix, resulting in an error at the parent directory fetch point.

**Comment by dmikurube** [comment]
If then, your fix seems like skipping the second file, right?  Is that an appropriate reaction?

I'm afraid that, what to be fixed could be `embulk-formatter-jsonl`, not this `embulk-output-sftp`?

What internal behavior and mechanism caused `"second output tasks treat the upload file as null, resulting in an error`?

**Comment by pn-koshikawa** [comment]
@dmikurube 
Thanks, I can work around the error, but not correctly. I will address this issue by modifying embulk-formatter-jsonl as you indicated so close this PR.

**Pull request closed without merging**
